/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./src/**/*.{html,ts}'],
  theme: {
    extend: {
      fontFamily: {
        sans: ['Outfit', 'system-ui', 'sans-serif'],
      },
    },
  },
  plugins: [require('daisyui')],
  daisyui: {
    themes: [
      {
        modern: {
          "primary": "#6366f1",
          "primary-content": "#ffffff",
          "secondary": "#8b5cf6",
          "secondary-content": "#ffffff",
          "accent": "#06b6d4",
          "accent-content": "#ffffff",
          "neutral": "#1e1e2e",
          "neutral-content": "#cdd6f4",
          "base-100": "#24243a",
          "base-200": "#1a1a2e",
          "base-300": "#12121f",
          "base-content": "#e2e8f0",
          "info": "#89b4fa",
          "info-content": "#1e1e2e",
          "success": "#a6e3a1",
          "success-content": "#1e1e2e",
          "warning": "#f9e2af",
          "warning-content": "#1e1e2e",
          "error": "#f38ba8",
          "error-content": "#1e1e2e",
        },
        light: {
          "primary": "#6366f1",
          "primary-content": "#ffffff",
          "secondary": "#8b5cf6",
          "secondary-content": "#ffffff",
          "accent": "#06b6d4",
          "accent-content": "#ffffff",
          "neutral": "#374151",
          "neutral-content": "#f3f4f6",
          "base-100": "#ffffff",
          "base-200": "#f1f5f9",
          "base-300": "#e2e8f0",
          "base-content": "#1e293b",
          "info": "#3b82f6",
          "info-content": "#ffffff",
          "success": "#22c55e",
          "success-content": "#ffffff",
          "warning": "#f59e0b",
          "warning-content": "#1f2937",
          "error": "#ef4444",
          "error-content": "#ffffff",
        },
      },
    ],
    darkTheme: "modern",
    base: true,
    styled: true,
    utils: true,
  },
};
